version: '3.8'

services:
  tdashcam-studio:
    image: ghcr.io/rodolfoconcepcion/tdashcamstudio:latest
    container_name: tdashcam-studio
    ports:
      - "8188:80"
    restart: unless-stopped
    environment:
      - TZ=America/Santo_Domingo
    networks:
      - tdashcam-network

networks:
  tdashcam-network:
    driver: bridge
